ur5_joint_positions:
  joints:
    - name: shoulder_pan_joint
      position: 0.0
    - name: shoulder_lift_joint
      position: -1.57
    - name: elbow_joint
      position: 1.57
    - name: wrist_1_joint
      position: 0.0
    - name: wrist_2_joint
      position: 0.0
    - name: wrist_3_joint
      position: 0.0
